name: Tests

on:
  push:
    - main
    - local-dev
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env')"

    - name: Install PHP Dependencies
      run: composer install --no-scripts
    
    - name: Install Node Dependencies
      run: npm install
    
    - name: Generate Application Key
      run: php artisan key:generate

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    
    - name: Execute Feature and Unit Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test